import React, { useState, useEffect } from "react";
import { useDispatch } from "react-redux";
import { registerUser } from "../store/slices/registerSlice";
import { validateForm } from "../utils/validateRegisterData";

const Register = () => {
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    gender: "",
    email: "",
    password: "",
    confirmPassword: "",
    birthday: "",
  });

  const dispatch = useDispatch();
  const [formIsValid, setFormIsValid] = useState({});

  useEffect(() => {
    // we do this kind of check because i know that if i have an error, i get back a object of errors generated by validate function
    // as soon as our form data is validated we dispatch the register action
    if (typeof formIsValid === "boolean" && formIsValid) {
      dispatch(registerUser(formData));
    }
  }, [formIsValid]);

  const handleSubmit = (event) => {
    // prevent the reload
    event.preventDefault();
    // we can only submit if we fill the required inputs, when submitting we only change the form is valid and let useEffect take care of dispatching the action..
    setFormIsValid(validateForm(formData));
  };

  const onChangeHandler = (event) => {
    const { name, value } = event.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  return (
    <div className="">
      <div>
        {/* Some design if provided */}
        <p></p>
      </div>
      <form
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "10px",
          alignItems: "flex-start",
        }}
        onSubmit={handleSubmit}
      >
        <label htmlFor="firstName">First Name:</label>
        {formIsValid.firstName && <p>{formIsValid.firstName}</p>}
        <input
          onChange={onChangeHandler}
          type="text"
          id="firstName"
          name="firstName"
          value={formData.firstName}
          required
        />

        <label htmlFor="lastName">Last Name:</label>
        {formIsValid.lastName && <p>{formIsValid.lastName}</p>}
        <input
          onChange={onChangeHandler}
          value={formData.lastName}
          type="text"
          id="lastName"
          name="lastName"
          required
        />

        <label htmlFor="email">Email:</label>
        <input
          onChange={onChangeHandler}
          value={formData.email}
          id="email"
          name="email"
          type="email"
          required
        />

        <label htmlFor="password">Password:</label>
        {formIsValid.password && <p>{formIsValid.password}</p>}

        <input
          onChange={onChangeHandler}
          value={formData.password}
          id="password"
          name="password"
          type="password"
          required
        />

        <label htmlFor="confirmPassword">Confirm Password:</label>
        {formIsValid.confirmPassword && !formIsValid.password && (
          <p>{formIsValid.confirmPassword}</p>
        )}

        <input
          onChange={onChangeHandler}
          value={formData.confirmPassword}
          id="confirmPassword"
          name="confirmPassword"
          type="password"
          required
        />

        <label htmlFor="gender">Gender:</label>
        <div>
          <label htmlFor="female">Female</label>
          <input
            onChange={onChangeHandler}
            type="radio"
            id="female"
            name="gender"
            value="Female"
            checked={formData.gender === "Female"}
            required
          />

          <label htmlFor="male">Male</label>
          <input
            onChange={onChangeHandler}
            type="radio"
            id="male"
            name="gender"
            value="Male"
            checked={formData.gender === "Male"}
            required
          />

          <label htmlFor="other">Other</label>
          <input
            onChange={onChangeHandler}
            type="radio"
            id="other"
            name="gender"
            value="Other"
            checked={formData.gender === "Other"}
            required
          />
        </div>

        <label htmlFor="birthday">Birthday:</label>
        {formIsValid.birthday && <p>{formIsValid.birthday}</p>}
        <input
          onChange={onChangeHandler}
          type="date"
          id="birthday"
          name="birthday"
          value={formData.birthday}
          required
        />

        <button type="submit">Submit</button>
      </form>
      <div>
        <p>Already have an account?</p>
        <a href="login">Log In</a>
      </div>
    </div>
  );
};

export default Register;
